/* eslint-disable @typescript-eslint/no-explicit-any */
export const LANGUAGES: any = {
  US: {
    WHATSAPP_TEXT: 'Contact Us',
    HERO_TEXT: {
      P1: 'PD Energy USA designs, installs, and maintains solar panels for homes.',
      P2: 'With solar energy, you can save on your energy bill, increase the value of your home, and become sustainable.',
      P3: 'Contact us to learn more.',
    },
    SERVICES_TEXT1: {
      TITLE: 'Home Solar Systems',
      P1: 'Achieve energy independence, reduce your electricity bill with PD Energy USA solar system.',
    },
    SERVICES_TEXT2: {
      TITLE: 'Panel Cleaning',
      P1: 'Cleaning the panel is essential for maximum performance of your system.',
    },
    SERVICES_TEXT3: {
      TITLE: 'Solar Battery',
      P1: 'You can store the energy generated by the panels using batteries, and use the energy when necessary.',
    },
    SERVICES_TEXT4: {
      TITLE: 'Electric Car Charger',
      P1: 'PD Energy USA installs and services electric vehicle chargers.',
    },
    FOOTER_TEXT: {
      FOOTER:
        'Copyright ©️ 2025 PD Energy USA. All rights reserved. Developed by',
    },
  },
  ES: {
    WHATSAPP_TEXT: 'Contáctenos',
    HERO_TEXT: {
      P1: 'PD Energy USA diseña, instala y mantiene paneles solares para hogares.',
      P2: 'Con la energía solar, puedes ahorrar en tu factura de electricidad, aumentar el valor de tu hogar y ser sostenible.',
      P3: 'Contáctanos para obtener más información.',
    },
    SERVICES_TEXT1: {
      TITLE: 'Sistemas Solares Residenciales',
      P1: 'Logra independencia energética, reduce tu factura de electricidad con el sistema solar de PD Energy USA.',
    },
    SERVICES_TEXT2: {
      TITLE: 'Limpieza de Paneles   ',
      P1: 'Limpiar los paneles es esencial para el máximo rendimiento de su sistema.',
    },
    SERVICES_TEXT3: {
      TITLE: 'Batería Solar',
      P1: 'Puede almacenar la energía generada por los paneles usando baterías y utilizar la energía cuando sea necesario.',
    },
    SERVICES_TEXT4: {
      TITLE: 'Cargador de Vehículo Eléctrico ',
      P1: 'PD Energy USA instala y da servicio a cargadores de vehículos eléctricos.',
    },
    FOOTER_TEXT: {
      FOOTER:
        'Copyright ©️ 2025 PD Energy USA. Todos los derechos reservados. Desarrollado por',
    },
  },
};
