import { useState } from 'react'; 'react'
import { BsWhatsapp } from 'react-icons/bs';
import Logo from './assets/images/logo-usa1.svg';
import Img from './assets/images/img2.jpg';
import Img3 from './assets/images/img3.png';
import Img4 from './assets/images/img4.png';
import Img5 from './assets/images/img5.png';


export const App = () => {


    
    const [language, setLanguage] = useState('us');
 
  return (    
    <div className='w-full'>
      <div className='flex justify-center items-center '>
        <div className='w-full'>
          <img
            src={Logo}
            className='2xl:w-1/2 xl:w-1/2 lg:w-1/2 w-3/4 2xl:mx-24 xl:mx-24 lg:mx-24 mx-6'
            alt='Logo PD Energy'
            title='Logo PD Energy'
          />
        </div>

        <nav className='w-full'>
          <ul className='flex justify-end 2xl:px-24 xl:px-24 lg:px-24 px-4'>
            <a
              href='https://api.whatsapp.com/send/?phone=5519991711316&text=Ol%C3%A1%21+Gostaria+de+mais+informa%C3%A7%C3%B5es+sobre+gera%C3%A7%C3%A3o+de+energia+solar+rural.'
              target='_blank'
              className='bg-[#498b00] text-white 2xl:text-xl xl:text-xl lg:text-xl text-xl 
              py-3 px-4 2xl:px-4 xl:px-4 lg:px-4 flex justify-center items-center 
              gap-3 rounded-xl my-12 cursor-pointer hover:bg-green-900'
            >
              <BsWhatsapp /> WhatsApp
            </a>
          </ul>
        </nav>
      </div>




      <div className='flex flex-col-2 justify-center itmns-center gap-2 mx-auto'>  
    <button onClick={() => setLanguage('New language')}
    className='bg-blue-500 text-white border-sm rounded-md p-2 mb-2'>English</button><br></br>
    <button onClick={() => setLanguage('New language')}
    className='bg-blue-500 text-white border-sm rounded-md p-2 mb-2'>Spanish</button>
      </div>






      <div className='bg-image'>
        <div className='w-full px-8 py-24 bg-black bg-opacity-50 flex justify-end items-center'>
          <div className='2xl:w-1/2 xl:w-1/2 lg:w-1/2 w-full'>
            <p className='text-white 2xl:text-3xl lg:text-3xl text-3xl text-center font-bold'>
              PD Energy USA designs, installs, and maintains solar panels for
              homes.<br></br>
              With solar energy, you can save on your energy bill, increase the
              value of your home, and become sustainable.<br></br>
              <br></br>
              Contact us to learn more.
            </p>

            <div className='w-full flex justify-center items-center mt-8'>
              <a
                href='https://api.whatsapp.com/send/?phone=5519991711316&text=Ol%C3%A1%21+Gostaria+de+mais+informa%C3%A7%C3%B5es+sobre+gera%C3%A7%C3%A3o+de+energia+solar+rural.'
                target='_blank'
                className='bg-[#498b00] text-white 2xl:text-xl xl:text-xl lg:text-xl text-lg py-3 px-4 
                        2xl:px-4 xl:px-4 lg:px-4 flex justify-center items-center gap-3 rounded-xl cursor-pointer hover:bg-green-900'
              >
                <BsWhatsapp /> Contact Us
              </a>
            </div>
          </div>
        </div>
      </div>






      <section className='w-full mt-20 mx-auto p-4 grid 2xl:grid-cols-2 xl:grid-cols-2 lg:grid-cols-2 grid-cols-1 justify-center items-center gap-6'>
      <div>
          <h2 className='text-center text-2xl text-green-600 font-bold'>
            Home Solar Systems
          </h2>
          <p className='text-slate-600 my-3 h-14 flex justify-center items-center'>
            Achieve energy independence, reduce your electricity bill with PD
            Energy USA's solar system.
          </p>
          <div className='w-full overflow-hidden'>
            <img
              src={Img}
              className='w-full justify-center border-2 border-slate-200 shadow-md rounded-md'
              alt='Home Solar Systems'
              title='Home Solar Systems'
            />
          </div>
        </div>

        <div>
          <h2 className='text-center text-2xl text-green-600 font-bold'>
            Panel Cleaning
          </h2>
          <p className='text-slate-600 my-3 h-14 flex justify-center items-center'>
            Cleaning the panel is essential for maximum performance of your system.
          </p>
          <div className='w-full overflow-hidden'>
            <img
              src={Img3}
              className='w-full justify-center border-lg rounded-md'
              alt='Panel cleaning'
              title='Panel cleaning'
            />
          </div>
        </div>

        <div>
          <h2 className='text-center text-2xl text-green-600 font-bold'>
            Solar Battery
          </h2>
          <p className='text-slate-600 my-3 h-14 flex justify-center items-center'>
            You can store the energy generated by the panels using batteries,
            and use the energy when necessary.
          </p>
          <div className='w-full overflow-hidden'>
            <img
              src={Img4}
              className='w-full justify-center'
              alt='Solar Battery'
              title='Solar Battery'
            />
          </div>
        </div>

        <div>
          <h2 className='text-center text-2xl text-green-600 font-bold'>
            Electric Car Charger
          </h2>
          <p className='text-slate-600 my-3 h-14 flex justify-center items-center'>
            PD Energy USA installs and services electric vehicle chargers.
          </p>
          <div className='w-full overflow-hidden'>
            <img
              src={Img5}
              className='w-full justify-center'
              alt='Electric Car Charger'
              title='Electric Car Charger'
            />
          </div>
        </div>
      </section>

      <section className='flex justify-center items-center mt-12'>
        <a
          href='https://api.whatsapp.com/send/?phone=5519991711316&text=Ol%C3%A1%21+Gostaria+de+mais+informa%C3%A7%C3%B5es+sobre+gera%C3%A7%C3%A3o+de+energia+solar+rural.'
          target='_blank'
          className='bg-[#498b00] text-white py-3 px-10 flex justify-center items-center gap-3 rounded-xl mb-20 cursor-pointer hover:bg-green-900'
        >
          <BsWhatsapp /> Contact Us
        </a>
      </section>

      <footer
        className='text-white bg-gradient-to-r 
        opacity-80 from-cyan-500 to-blue-500 py-12 px-20 
        shadow-lg w-full text-center text-sm m-auto'
      >
        Copyright © 2024 PD Energy USA. All rights reserved. Developed by
        <a href='http://missura.com.br'
          target='_blank'
          className='text-white hover:text-black'>
          {' '}
          Missura Networks.
        </a>
      </footer>
    </div>
  );
};
